env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-undef:
    - warn
  no-console:
    - warn
  no-var:
    - error
  no-unused-vars:
    - warn
  prefer-const:
    - warn
  prefer-arrow-callback:
    - error
